### ISSUE TITLE
Unused required dependencies

### ISSUE THREAD

**Issue by francois-rozet** [v0lta/Jax-Wavelet-Toolbox#9]
Hello, thanks for the package. Would it be possible to remove the dependencies that are not used by the package like `matplotlib`, `nox`, `pooch`, `pytest` ... from the `setup.cfg`? These are only necessary for contributing to `jaxwt` but not for installing it.

https://github.com/v0lta/Jax-Wavelet-Toolbox/blob/9288c9b4b8a803df2c389e549ceff6dced501474/setup.cfg#L46-L56

**Comment by v0lta** [comment]
Yes, I am currently on vacation. I will get to this next week when I am back.

**Comment by v0lta** [comment]
The current development release comes with a fix. Until the next release installing via:
``` bash
pip install git+ssh://git@github.com/v0lta/Jax-Wavelet-Toolbox.git@master
```
should fix your issue.

**Comment by v0lta** [comment]
https://github.com/v0lta/Jax-Wavelet-Toolbox/releases/tag/v0.1.1 should fix this. Feel free to reopen this issue if I missed something.

**Comment by francois-rozet** [comment]
Thanks!
